package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.VerticalScrollArrangement;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.BarcodeScanner;
import com.google.appinventor.components.runtime.TinyDB;
class Izbire extends Form implements HandlesEventDispatching {
  private HorizontalArrangement Okvir_naslov;
  private HorizontalArrangement BlažilecNaslov2;
  private Image Logo;
  private HorizontalArrangement BlažilecNaslov;
  private Label Naslov;
  private HorizontalArrangement Barvna_crta1;
  private VerticalScrollArrangement Scroll_Okvir_Kontrolnih_Tock;
  private HorizontalArrangement Blažilec_pred_naslovom;
  private Label Podnaslov;
  private HorizontalArrangement BlažilecKT1;
  private HorizontalArrangement OkvirKT1;
  private Button ScanKT1;
  private HorizontalArrangement blaz1;
  private HorizontalArrangement OkvirInfoKT1;
  private Image Info1;
  private HorizontalArrangement blazi1;
  private HorizontalArrangement OkvirSlikaKT1;
  private Image kljukica1;
  private HorizontalArrangement BlažilecKT2;
  private HorizontalArrangement OkvirKT2;
  private Button ScanKT2;
  private HorizontalArrangement blaz2;
  private HorizontalArrangement OkvirInfoKT2;
  private Image Info2;
  private HorizontalArrangement blazi2;
  private HorizontalArrangement OkvirSlikaKT2;
  private Image kljukica2;
  private HorizontalArrangement BlažilecKT3;
  private HorizontalArrangement OkvirKT3;
  private Button ScanKT3;
  private HorizontalArrangement blaz3;
  private HorizontalArrangement OkvirInfoKT3;
  private Image Info3;
  private HorizontalArrangement blazi3;
  private HorizontalArrangement OkvirSlikaKT3;
  private Image kljukica3;
  private HorizontalArrangement BlažilecKT4;
  private HorizontalArrangement OkvirKT4;
  private Button ScanKT4;
  private HorizontalArrangement blaz4;
  private HorizontalArrangement OkvirInfoKT4;
  private Image Info4;
  private HorizontalArrangement blazi4;
  private HorizontalArrangement OkvirSlikaKT4;
  private Image kljukica4;
  private HorizontalArrangement BlažilecKT5;
  private HorizontalArrangement OkvirKT5;
  private Button ScanKT5;
  private HorizontalArrangement blaz5;
  private HorizontalArrangement OkvirInfoKT5;
  private Image Info5;
  private HorizontalArrangement blazi5;
  private HorizontalArrangement OkvirSlikaKT5;
  private Image kljukica5;
  private HorizontalArrangement BlažilecKT6;
  private HorizontalArrangement OkvirKT6;
  private Button ScanKT6;
  private HorizontalArrangement blaz6;
  private HorizontalArrangement OkvirInfoKT6;
  private Image Info6;
  private HorizontalArrangement blazi6;
  private HorizontalArrangement OkvirSlikaKT6;
  private Image kljukica6;
  private HorizontalArrangement BlažilecKT7;
  private HorizontalArrangement OkvirKT7;
  private Button ScanKT7;
  private HorizontalArrangement blaz7;
  private HorizontalArrangement OkvirInfoKT7;
  private Image Info7;
  private HorizontalArrangement blazi7;
  private HorizontalArrangement OkvirSlikaKT7;
  private Image kljukica7;
  private HorizontalArrangement BlažilecKT8;
  private HorizontalArrangement OkvirKT8;
  private Button ScanKT8;
  private HorizontalArrangement blaz8;
  private HorizontalArrangement OkvirInfoKT8;
  private Image Info8;
  private HorizontalArrangement blazi8;
  private HorizontalArrangement OkvirSlikaKT8;
  private Image kljukica8;
  private HorizontalArrangement BlažilecKT9;
  private HorizontalArrangement OkvirKT9;
  private Button ScanKT9;
  private HorizontalArrangement blaz9;
  private HorizontalArrangement OkvirInfoKT9;
  private Image Info9;
  private HorizontalArrangement blazi9;
  private HorizontalArrangement OkvirSlikaKT9;
  private Image kljukica9;
  private HorizontalArrangement BlažilecKT10;
  private HorizontalArrangement OkvirKT10;
  private Button ScanKT10;
  private HorizontalArrangement blaz10;
  private HorizontalArrangement OkvirInfoKT10;
  private Image Info10;
  private HorizontalArrangement blazi10;
  private HorizontalArrangement OkvirSlikaKT10;
  private Image kljukica10;
  private HorizontalArrangement BlažilecKT11;
  private HorizontalArrangement Barvna_crta2;
  private HorizontalArrangement Okvir_spodnji_menu;
  private VerticalArrangement Okvir_informacije;
  private Image Informacije_slika;
  private Label Informacije;
  private VerticalArrangement Okvir_navodila_za_pot;
  private Image Navodila_za_pot_slika;
  private Label NavodilaPot;
  private VerticalArrangement Okvir_zemljevid;
  private Image Zemljevid_slika;
  private Label Zemljevid;
  private VerticalArrangement Okvir_znova;
  private Label Label3;
  private Label Znova;
  private BarcodeScanner BarcodeScanner1;
  private TinyDB TinyDB1;
  protected void $define() {
    this.AlignHorizontal(3);
    this.AppName("BREST");
    this.Title("Izbire");
    Okvir_naslov = new HorizontalArrangement(this);
    Okvir_naslov.AlignHorizontal(3);
    Okvir_naslov.AlignVertical(2);
    Okvir_naslov.Height(-1010);
    Okvir_naslov.Width(LENGTH_FILL_PARENT);
    BlažilecNaslov2 = new HorizontalArrangement(Okvir_naslov);
    BlažilecNaslov2.Width(-1002);
    Logo = new Image(Okvir_naslov);
    Logo.Height(-1010);
    Logo.Width(-1020);
    Logo.Picture("Logotip1.jpg");
    BlažilecNaslov = new HorizontalArrangement(Okvir_naslov);
    BlažilecNaslov.Width(-1002);
    Naslov = new Label(Okvir_naslov);
    Naslov.FontBold(true);
    Naslov.FontSize(18);
    Naslov.Width(-1075);
    Naslov.Text("Pohod\n po sledeh soške fronte");
    Barvna_crta1 = new HorizontalArrangement(this);
    Barvna_crta1.BackgroundColor(0xFF000000);
    Barvna_crta1.Height(-1001);
    Barvna_crta1.Width(LENGTH_FILL_PARENT);
    Scroll_Okvir_Kontrolnih_Tock = new VerticalScrollArrangement(this);
    Scroll_Okvir_Kontrolnih_Tock.AlignHorizontal(3);
    Scroll_Okvir_Kontrolnih_Tock.Height(-1078);
    Scroll_Okvir_Kontrolnih_Tock.Width(LENGTH_FILL_PARENT);
    Blažilec_pred_naslovom = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    Blažilec_pred_naslovom.Height(-1002);
    Podnaslov = new Label(Scroll_Okvir_Kontrolnih_Tock);
    Podnaslov.FontBold(true);
    Podnaslov.FontSize(24);
    Podnaslov.Text("Kontrolne točke");
    BlažilecKT1 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT1.Height(-1002);
    OkvirKT1 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT1.AlignHorizontal(3);
    OkvirKT1.AlignVertical(2);
    OkvirKT1.Height(-1010);
    OkvirKT1.Width(LENGTH_FILL_PARENT);
    ScanKT1 = new Button(OkvirKT1);
    ScanKT1.FontBold(true);
    ScanKT1.FontSize(14);
    ScanKT1.Width(-1060);
    ScanKT1.Shape(1);
    ScanKT1.Text("KT1\nStara šola");
    blaz1 = new HorizontalArrangement(OkvirKT1);
    blaz1.Width(-1003);
    OkvirInfoKT1 = new HorizontalArrangement(OkvirKT1);
    OkvirInfoKT1.Width(-1015);
    Info1 = new Image(OkvirInfoKT1);
    Info1.Width(-1015);
    Info1.Picture("Info1brez.png");
    blazi1 = new HorizontalArrangement(OkvirKT1);
    blazi1.Width(-1003);
    OkvirSlikaKT1 = new HorizontalArrangement(OkvirKT1);
    OkvirSlikaKT1.Width(-1015);
    kljukica1 = new Image(OkvirSlikaKT1);
    kljukica1.Width(-1015);
    kljukica1.Picture("OK1brez.png");
    BlažilecKT2 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT2.Height(-1001);
    OkvirKT2 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT2.AlignHorizontal(3);
    OkvirKT2.AlignVertical(2);
    OkvirKT2.Height(-1010);
    OkvirKT2.Width(LENGTH_FILL_PARENT);
    ScanKT2 = new Button(OkvirKT2);
    ScanKT2.FontBold(true);
    ScanKT2.FontSize(14);
    ScanKT2.Width(-1060);
    ScanKT2.Shape(1);
    ScanKT2.Text("KT2\nKriž na Polju");
    blaz2 = new HorizontalArrangement(OkvirKT2);
    blaz2.Width(-1003);
    OkvirInfoKT2 = new HorizontalArrangement(OkvirKT2);
    OkvirInfoKT2.Width(-1015);
    Info2 = new Image(OkvirInfoKT2);
    Info2.Width(-1015);
    Info2.Picture("Info1brez.png");
    blazi2 = new HorizontalArrangement(OkvirKT2);
    blazi2.Width(-1003);
    OkvirSlikaKT2 = new HorizontalArrangement(OkvirKT2);
    OkvirSlikaKT2.Width(-1015);
    kljukica2 = new Image(OkvirSlikaKT2);
    kljukica2.Width(-1015);
    kljukica2.Picture("OK1brez.png");
    BlažilecKT3 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT3.Height(-1001);
    OkvirKT3 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT3.AlignHorizontal(3);
    OkvirKT3.AlignVertical(2);
    OkvirKT3.Height(-1010);
    OkvirKT3.Width(LENGTH_FILL_PARENT);
    ScanKT3 = new Button(OkvirKT3);
    ScanKT3.FontBold(true);
    ScanKT3.FontSize(14);
    ScanKT3.Width(-1060);
    ScanKT3.Shape(1);
    ScanKT3.Text("KT3\nCerkev sv. Anastazije");
    blaz3 = new HorizontalArrangement(OkvirKT3);
    blaz3.Width(-1003);
    OkvirInfoKT3 = new HorizontalArrangement(OkvirKT3);
    OkvirInfoKT3.Width(-1015);
    Info3 = new Image(OkvirInfoKT3);
    Info3.Width(-1015);
    Info3.Picture("Info1brez.png");
    blazi3 = new HorizontalArrangement(OkvirKT3);
    blazi3.Width(-1003);
    OkvirSlikaKT3 = new HorizontalArrangement(OkvirKT3);
    OkvirSlikaKT3.Width(-1015);
    kljukica3 = new Image(OkvirSlikaKT3);
    kljukica3.Width(-1015);
    kljukica3.Picture("OK1brez.png");
    BlažilecKT4 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT4.Height(-1001);
    OkvirKT4 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT4.AlignHorizontal(3);
    OkvirKT4.AlignVertical(2);
    OkvirKT4.Height(-1010);
    OkvirKT4.Width(LENGTH_FILL_PARENT);
    ScanKT4 = new Button(OkvirKT4);
    ScanKT4.FontBold(true);
    ScanKT4.FontSize(14);
    ScanKT4.Width(-1060);
    ScanKT4.Shape(1);
    ScanKT4.Text("KT4\nKucelj");
    blaz4 = new HorizontalArrangement(OkvirKT4);
    blaz4.Width(-1003);
    OkvirInfoKT4 = new HorizontalArrangement(OkvirKT4);
    OkvirInfoKT4.Width(-1015);
    Info4 = new Image(OkvirInfoKT4);
    Info4.Width(-1015);
    Info4.Picture("Info1brez.png");
    blazi4 = new HorizontalArrangement(OkvirKT4);
    blazi4.Width(-1003);
    OkvirSlikaKT4 = new HorizontalArrangement(OkvirKT4);
    OkvirSlikaKT4.Width(-1015);
    kljukica4 = new Image(OkvirSlikaKT4);
    kljukica4.Width(-1015);
    kljukica4.Picture("OK1brez.png");
    BlažilecKT5 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT5.Height(-1001);
    OkvirKT5 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT5.AlignHorizontal(3);
    OkvirKT5.AlignVertical(2);
    OkvirKT5.Height(-1010);
    OkvirKT5.Width(LENGTH_FILL_PARENT);
    ScanKT5 = new Button(OkvirKT5);
    ScanKT5.FontBold(true);
    ScanKT5.FontSize(14);
    ScanKT5.Width(-1060);
    ScanKT5.Shape(1);
    ScanKT5.Text("KT5\nKaverna Moritz");
    blaz5 = new HorizontalArrangement(OkvirKT5);
    blaz5.Width(-1003);
    OkvirInfoKT5 = new HorizontalArrangement(OkvirKT5);
    OkvirInfoKT5.Width(-1015);
    Info5 = new Image(OkvirInfoKT5);
    Info5.Width(-1015);
    Info5.Picture("Info1brez.png");
    blazi5 = new HorizontalArrangement(OkvirKT5);
    blazi5.Width(-1003);
    OkvirSlikaKT5 = new HorizontalArrangement(OkvirKT5);
    OkvirSlikaKT5.Width(-1015);
    kljukica5 = new Image(OkvirSlikaKT5);
    kljukica5.Width(-1015);
    kljukica5.Picture("OK1brez.png");
    BlažilecKT6 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT6.Height(-1001);
    OkvirKT6 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT6.AlignHorizontal(3);
    OkvirKT6.AlignVertical(2);
    OkvirKT6.Height(-1010);
    OkvirKT6.Width(LENGTH_FILL_PARENT);
    ScanKT6 = new Button(OkvirKT6);
    ScanKT6.FontBold(true);
    ScanKT6.FontSize(14);
    ScanKT6.Width(-1060);
    ScanKT6.Shape(1);
    ScanKT6.Text("KT6\nObmejna stražnica");
    blaz6 = new HorizontalArrangement(OkvirKT6);
    blaz6.Width(-1003);
    OkvirInfoKT6 = new HorizontalArrangement(OkvirKT6);
    OkvirInfoKT6.Width(-1015);
    Info6 = new Image(OkvirInfoKT6);
    Info6.Width(-1015);
    Info6.Picture("Info1brez.png");
    blazi6 = new HorizontalArrangement(OkvirKT6);
    blazi6.Width(-1003);
    OkvirSlikaKT6 = new HorizontalArrangement(OkvirKT6);
    OkvirSlikaKT6.Width(-1015);
    kljukica6 = new Image(OkvirSlikaKT6);
    kljukica6.Width(-1015);
    kljukica6.Picture("OK1brez.png");
    BlažilecKT7 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT7.Height(-1001);
    OkvirKT7 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT7.AlignHorizontal(3);
    OkvirKT7.AlignVertical(2);
    OkvirKT7.Height(-1010);
    OkvirKT7.Width(LENGTH_FILL_PARENT);
    ScanKT7 = new Button(OkvirKT7);
    ScanKT7.FontBold(true);
    ScanKT7.FontSize(14);
    ScanKT7.Width(-1060);
    ScanKT7.Shape(1);
    ScanKT7.Text("KT7\nGrofova jama");
    blaz7 = new HorizontalArrangement(OkvirKT7);
    blaz7.Width(-1003);
    OkvirInfoKT7 = new HorizontalArrangement(OkvirKT7);
    OkvirInfoKT7.Width(-1015);
    Info7 = new Image(OkvirInfoKT7);
    Info7.Width(-1015);
    Info7.Picture("Info1brez.png");
    blazi7 = new HorizontalArrangement(OkvirKT7);
    blazi7.Width(-1003);
    OkvirSlikaKT7 = new HorizontalArrangement(OkvirKT7);
    OkvirSlikaKT7.Width(-1015);
    kljukica7 = new Image(OkvirSlikaKT7);
    kljukica7.Width(-1015);
    kljukica7.Picture("OK1brez.png");
    BlažilecKT8 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT8.Height(-1001);
    OkvirKT8 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT8.AlignHorizontal(3);
    OkvirKT8.AlignVertical(2);
    OkvirKT8.Height(-1010);
    OkvirKT8.Width(LENGTH_FILL_PARENT);
    ScanKT8 = new Button(OkvirKT8);
    ScanKT8.FontBold(true);
    ScanKT8.FontSize(14);
    ScanKT8.Width(-1060);
    ScanKT8.Shape(1);
    ScanKT8.Text("KT8\nOstanki gradišča");
    blaz8 = new HorizontalArrangement(OkvirKT8);
    blaz8.Width(-1003);
    OkvirInfoKT8 = new HorizontalArrangement(OkvirKT8);
    OkvirInfoKT8.Width(-1015);
    Info8 = new Image(OkvirInfoKT8);
    Info8.Width(-1015);
    Info8.Picture("Info1brez.png");
    blazi8 = new HorizontalArrangement(OkvirKT8);
    blazi8.Width(-1003);
    OkvirSlikaKT8 = new HorizontalArrangement(OkvirKT8);
    OkvirSlikaKT8.Width(-1015);
    kljukica8 = new Image(OkvirSlikaKT8);
    kljukica8.Width(-1015);
    kljukica8.Picture("OK1brez.png");
    BlažilecKT9 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT9.Height(-1001);
    OkvirKT9 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT9.AlignHorizontal(3);
    OkvirKT9.AlignVertical(2);
    OkvirKT9.Height(-1010);
    OkvirKT9.Width(LENGTH_FILL_PARENT);
    ScanKT9 = new Button(OkvirKT9);
    ScanKT9.FontBold(true);
    ScanKT9.FontSize(14);
    ScanKT9.Width(-1060);
    ScanKT9.Shape(1);
    ScanKT9.Text("KT9\nOstanki apnenice");
    blaz9 = new HorizontalArrangement(OkvirKT9);
    blaz9.Width(-1003);
    OkvirInfoKT9 = new HorizontalArrangement(OkvirKT9);
    OkvirInfoKT9.Width(-1015);
    Info9 = new Image(OkvirInfoKT9);
    Info9.Width(-1015);
    Info9.Picture("Info1brez.png");
    blazi9 = new HorizontalArrangement(OkvirKT9);
    blazi9.Width(-1003);
    OkvirSlikaKT9 = new HorizontalArrangement(OkvirKT9);
    OkvirSlikaKT9.Width(-1015);
    kljukica9 = new Image(OkvirSlikaKT9);
    kljukica9.Width(-1015);
    kljukica9.Picture("OK1brez.png");
    BlažilecKT10 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT10.Height(-1001);
    OkvirKT10 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    OkvirKT10.AlignHorizontal(3);
    OkvirKT10.AlignVertical(2);
    OkvirKT10.Height(-1010);
    OkvirKT10.Width(LENGTH_FILL_PARENT);
    ScanKT10 = new Button(OkvirKT10);
    ScanKT10.FontBold(true);
    ScanKT10.FontSize(14);
    ScanKT10.Width(-1060);
    ScanKT10.Shape(1);
    ScanKT10.Text("KT10\nCerkev sv. Lovrenca");
    blaz10 = new HorizontalArrangement(OkvirKT10);
    blaz10.Width(-1003);
    OkvirInfoKT10 = new HorizontalArrangement(OkvirKT10);
    OkvirInfoKT10.Width(-1015);
    Info10 = new Image(OkvirInfoKT10);
    Info10.Width(-1015);
    Info10.Picture("Info1brez.png");
    blazi10 = new HorizontalArrangement(OkvirKT10);
    blazi10.Width(-1003);
    OkvirSlikaKT10 = new HorizontalArrangement(OkvirKT10);
    OkvirSlikaKT10.Width(-1015);
    kljukica10 = new Image(OkvirSlikaKT10);
    kljukica10.Width(-1015);
    kljukica10.Picture("OK1brez.png");
    BlažilecKT11 = new HorizontalArrangement(Scroll_Okvir_Kontrolnih_Tock);
    BlažilecKT11.Height(-1001);
    Barvna_crta2 = new HorizontalArrangement(this);
    Barvna_crta2.BackgroundColor(0xFF000000);
    Barvna_crta2.Height(-1001);
    Barvna_crta2.Width(LENGTH_FILL_PARENT);
    Okvir_spodnji_menu = new HorizontalArrangement(this);
    Okvir_spodnji_menu.AlignHorizontal(3);
    Okvir_spodnji_menu.AlignVertical(3);
    Okvir_spodnji_menu.Height(-1010);
    Okvir_spodnji_menu.Width(LENGTH_FILL_PARENT);
    Okvir_informacije = new VerticalArrangement(Okvir_spodnji_menu);
    Okvir_informacije.AlignHorizontal(3);
    Okvir_informacije.AlignVertical(2);
    Okvir_informacije.Width(-1024);
    Informacije_slika = new Image(Okvir_informacije);
    Informacije_slika.Width(-1010);
    Informacije_slika.Picture("Vprasaj1brez.png");
    Informacije = new Label(Okvir_informacije);
    Informacije.FontBold(true);
    Informacije.FontSize(8);
    Informacije.Height(-1003);
    Informacije.Text("Informacije");
    Okvir_navodila_za_pot = new VerticalArrangement(Okvir_spodnji_menu);
    Okvir_navodila_za_pot.AlignHorizontal(3);
    Okvir_navodila_za_pot.AlignVertical(2);
    Okvir_navodila_za_pot.Width(-1024);
    Navodila_za_pot_slika = new Image(Okvir_navodila_za_pot);
    Navodila_za_pot_slika.Width(-1010);
    Navodila_za_pot_slika.Picture("Navodila1brez.png");
    NavodilaPot = new Label(Okvir_navodila_za_pot);
    NavodilaPot.FontBold(true);
    NavodilaPot.FontSize(8);
    NavodilaPot.Height(-1003);
    NavodilaPot.Text("Navodila za pot");
    Okvir_zemljevid = new VerticalArrangement(Okvir_spodnji_menu);
    Okvir_zemljevid.AlignHorizontal(3);
    Okvir_zemljevid.AlignVertical(2);
    Okvir_zemljevid.Width(-1024);
    Zemljevid_slika = new Image(Okvir_zemljevid);
    Zemljevid_slika.Width(-1010);
    Zemljevid_slika.Picture("Kompas1brez.png");
    Zemljevid = new Label(Okvir_zemljevid);
    Zemljevid.FontBold(true);
    Zemljevid.FontSize(8);
    Zemljevid.Height(-1003);
    Zemljevid.Text("Zemljevid poti");
    Okvir_znova = new VerticalArrangement(Okvir_spodnji_menu);
    Okvir_znova.AlignHorizontal(3);
    Okvir_znova.AlignVertical(2);
    Okvir_znova.Width(-1024);
    Label3 = new Label(Okvir_znova);
    Label3.FontBold(true);
    Label3.FontSize(28);
    Label3.Width(-1010);
    Label3.Text("0");
    Label3.TextColor(0xFF21AA28);
    Znova = new Label(Okvir_znova);
    Znova.FontBold(true);
    Znova.FontSize(8);
    Znova.Height(-1003);
    Znova.Text("Število pohodov");
    BarcodeScanner1 = new BarcodeScanner(this);
    BarcodeScanner1.UseExternalScanner(false);
    TinyDB1 = new TinyDB(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}